[Params]
  description = "Yet another analog photo blog - photograpy with cameras from the flea market."
  disableScale = true
  copyrightYears = "2016 - 2026"
  linkTumblr = true
  wikidata = true

[params.author]
  email = 'mail@christianmahnke.de'
  name = 'Christian Mahnke'
  uri = 'http://www.wikidata.org/entity/Q137668638'
